name: AnbuCapture
version: 1.3.4-beta
authors: [WiseHollow, mjl1010]
main: net.johnbrooks.mh.Main
api-version: '1.16'
softdepend: [Vault, GriefPrevention, Towny, Residence]
permissions:
  MobCapture.Admin:
    description: Performs administrative tasks regarding MobCapture.
    default: op
  MobCapture.Catch.*:
    description: Ability to capture all types of animals and monsters.
    default: op
  MobCapture.Catch.Peaceful:
    description: Ability to capture animals.
    default: op
  MobCapture.Catch.Hostile:
    description: Ability to capture monsters.
    default: op
  MobCapture.NoCost:
    description: Capture creatures without a cost.
    default: op
commands:
  MobCapture:
    description: Performs administrative tasks regarding MobCapture.
    usage: /<command> reload|update|version|spawn
    permission: MobCapture.admin
    permission-message: You don't have <permission>
  capturar:
    description: Performs administrative tasks regarding MobCapture.
    usage: /<command> reload|update|version|spawn
    permission: MobCapture.admin
    permission-message: You don't have <permission>